### ISSUE TITLE
Add header to authenticated request/messsage

### ISSUE THREAD

**Issue by salyh** [elastic/shield-custom-realm-example#1]
It seems currently not possible to add a header to an authenticated restrequest/transportmesssage. This is only possible in the AuthenticationFailureHandler when things go wrong. Adding headers to the final HTTP 200 message would be required for implementing GSSAPI mechanisms IMHO. Any plans/advices here?

**Comment by jaymode** [comment]
Hi @salyh,

You are correct. As realms are currently implemented, we do not intercept the responses of messages or have a way to add such a header on a success. We are looking at how we can enable this type of functionality.

When you refer to GSSAPI, are you mainly thinking of HTTP SPNEGO based Kerberos(RFC 4559)? In terms of an immediate solution/workaround, this type of authentication can work without the final token in the HTTP 200 response. The proper solution though is to comply with the RFC and always send back the token if there is one to return.

**Comment by salyh** [comment]
Exactly, i am working on a SPNEGO Realm for Shield.

**Comment by salyh** [comment]
Kerberos Realm is released: https://github.com/codecentric/elasticsearch-shield-kerberos-realm

**Comment by salyh** [comment]
Any updates?

**Comment by jaymode** [comment]
This should be possible in the next major version since we changed how we handle headers and context with requests in elasticsearch. I do not think we will have anything before then

**Comment by jaymode** [comment]
@salyh this is now possible in the 5.0 series. You can add the `ThreadContext` to your token during extraction and then in the `authenticate` method you can call `ThreadContext#addResponseHeader`.
