### ISSUE TITLE
Update the custom shield realm to 5.1.x

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/shield-custom-realm-example#12]
We should update this realm to expose the changes in 5.1 .

@jaymode any chance we can include this?

Also, seems that one of the methods: 

```
public Map<String, Factory> getRealms() {
```

Changed to:
 

```
public Map<String, Factory> getRealms(final ResourceWatcherService service) {
```

Are there any other significant changes added to this? 

Thanks!

**Comment by jaymode** [comment]
No other changes. Closed by 8645b0b353e1f2a3152599b484503664cefd192a
