### ISSUE TITLE
Failed to apply plugin [id 'carrotsearch.randomized-testing'] on ./gradlew build

### ISSUE THREAD

**Issue by bric3** [elastic/shield-custom-realm-example#16]
Hi I just clone this project on master, and I have issues building the project, what is wrong with my setup? 

```sh
shield-custom-realm-example ± ❯ ./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/brice/work/renault/shield-custom-realm-example/build.gradle' line: 39

* What went wrong:
A problem occurred evaluating root project 'x-pack-custom-realm-extension-example'.
> Failed to apply plugin [id 'carrotsearch.randomized-testing']
   > Could not generate a proxy class for class com.carrotsearch.gradle.junit4.RandomizedTestingTask.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.666 secs
```
_I didn't include `--stacktrace` or `--info` logs as those don't seem to give any sueful information regarding the carrotsearch plugin._

```sh
shield-custom-realm-example ± ❯ ./gradlew -v

------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Mac OS X 10.12.5 x86_64

shield-custom-realm-example ± ❯ git log -1
commit b0e41f76cc4be8f61ed3f4b52e9113da9c553ddb (HEAD -> master, origin/master, origin/HEAD)
Merge: 586d5d6 4168a50
Author: Tal Levy <JubBoy333@gmail.com>
Date:   2017-06-01 07:14:12 -0700

    Merge pull request #15 from talevy/master
    
    update to 5.4.0
```

**Comment by bric3** [comment]
Ha it seems that up to version 5.3, the necessary version of gradle was 2.13.

Switching to gradle 3.5, fixed things. **The readme should be updated to mention this**

**Comment by bric3** [comment]
Thanks @jaymode

**Comment by bric3** [comment]
By the @jaymode Do you know how to disable some plugins, imported via the elasticsearch plugin. I would like to avoid using `carrotsearch.randomized-testing` in my setup.

**Comment by jaymode** [comment]
@bric3 in that case, you'll want to setup a different build and test infrastructure for your project. We make extensive use of randomized testing at elastic. In general you can use the same dependencies to build your own extension and just ensure it is packaged in a structure that matches how this example is packaged.

**Comment by bric3** [comment]
@jaynode, yes I understand this makes sense to make such tests. My plugin for shield is way more simple. 

But I'd like nice stuff like running a integration server, from gradle, like it was possible with maven/ant, and the api usage verification (like forbidden APIs)

**Comment by jaymode** [comment]
I see. You can still pull in the build tools as a dependency but maybe need to create a different plugin in gradle to not use the randomized testing. The base build plugin relies on randomized testing https://github.com/elastic/elasticsearch/blob/v5.4.0/buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy

**Comment by bric3** [comment]
@jaymode That looks complicated given the simplicity of my plugin (I'm porting one that has been made for ES 2.3)
