### ISSUE TITLE
Can you please generate a scaffolding for 5.5.1?

### ISSUE THREAD

**Issue by michaelhidalgo** [elastic/shield-custom-realm-example#20]
Hi folks, can you please create and compile a version for 5.5.*?

**Comment by michaelhidalgo** [comment]
Hi @jaymode I saw you were the last who generated previous version, can you help on this? I could send the PR but this means we need a new branch.

**Comment by jaymode** [comment]
@albertzaharovits has pushed for https://github.com/elastic/shield-custom-realm-example/commit/39ee77bfcfb703a8a2c635bc2f8949475d419b93 for 5.5.1

**Comment by michaelhidalgo** [comment]
thanks @albertzaharovits , will you keep the same name convention on 6.0?

Thanks.

**Comment by albertzaharovits** [comment]
The API is changed a bit in 6.0 but the structure will be similar and there will be a scaffolding.
We are working towards Single Sign On (SSO) were the Elasticsearch is the Service Provider (SP). In this situation we expect the interest for custom authn realms to decrease.

**Comment by michaelhidalgo** [comment]
thanks @albertzaharovits , if there is some documentation around the SSO integration, I'm very interested on give it a try, however, I have not found so much documentation that explains the architecture from a development perspective.

In particular I want to configure the realm to authenticate against a REST API. SSO sounds like useful on this scenario so I appreciate any documentation you have.


thanks.

**Comment by albertzaharovits** [comment]
@michaelhidalgo 
SSO is still in development, there is no external documentation available. Specifically we will support  a variant of the `Web Browser SSO Profile`. You can get familiar with the flow from the official documentation e.g. [https://www.oasis-open.org/committees/download.php/27819/sstc-saml-tech-overview-2.0-cd-02.pdf](OASIS SAML Overview).
Fo your usecase the SAML Realm will be configured to use an external Identity Provider (IdP) and the REST API call will be done at that specific Idp. If you want to bypass the IdP (this is not SSO) and authn via REST API, the Custom Realm is the way to go.

**Comment by michaelhidalgo** [comment]
Thanks for the information @albertzaharovits , my concern is if at some point your team will stop supporting the custom realm architecture in the near future.

This is part of the risk management I'm trying to address at this stage (since it involves some development from our side) my concern is if at some point in the near future your team decides to get rid of the schema based on custom realms or if the implementation will considerable change on version 6.0.

We will do informed decisions based on that criteria.

Thanks.

**Comment by tvernum** [comment]
We are not able to make commitments regarding future releases in this sort of forum.
If you need something specific, please talk to your account manager who can liase with our product managers to help you out.

_However_
You can download beta1 of 6.0 right now.
The API in that release is a little different to API in 5.x, but it's not a big change. We intend to provide an updated sample of a 6.0 custom realm _before_ the official release of Elasticsearch 6.0. 
We also have no _plans_ to change the API again between now and the 6.0 release, but the purpose of a beta release is to find bugs and fix things, so it's possible we will need to tweak something.

We've made some general statements at Elastic{ON} and Elastic{ON}Tour that we intend (in some future release) to provide more builtin realms types around SAML/OAuth/Kerberos. As we do so, we expect that will _reduce_ the need for people to produce their own custom realms, but that does not mean that we intend to remove or deprecate custom realms.
