### ISSUE TITLE
Error during build: "Gradle 4.2 is not compatible with the elasticsearch build"

### ISSUE THREAD

**Issue by Mulder8472** [elastic/shield-custom-realm-example#28]
Hi, Im usually not a Gradle user, so excuse me if there is an easy fix, but when I check out the repo and run "gradle", I get this error message: "Gradle 4.2 is not compatible with the elasticsearch build"

Your readme tells me that I need Gradle 3.3 or newer. Do I have to install a 3.x version?

**Comment by Mulder8472** [comment]
I just tried with gradle 3.5.1 and the build succeeded.

**Comment by jaymode** [comment]
We now use the gradle wrapper so this can be avoided in the future.
