### ISSUE TITLE
updating to 6.2.1 has issues

### ISSUE THREAD

**Issue by vshank77** [elastic/shield-custom-realm-example#30]
Couple of issues when trying to upgrade to elasticsearch 6.2.1 

1) Missing CachingRealm - `org.elasticsearch.xpack.security.authc.support.CachingRealm` - while all other classes have been migrated from `xpack.security` to `xpack.core.security`, this class has completely gone missing. Can you please confirm that this is by design and not missing anything.

2)  problem occurred evaluating root project 'x-pack-custom-realm-extension-example'.
> Failed to apply plugin [id 'elasticsearch.build']
   > Java 1.9 or above is required to build Elasticsearch

Can you please confirm that we cannot build elasticsearch with Java 8 anymore. Thanks

**Comment by vshank77** [comment]
Happy to resolve the issues and submit a PR.

**Comment by inqueue** [comment]
Hi @vshank77, item 2. is correct. Elasticsearch must be built with Java 1.9. Perhaps @tvernum or @jaymode can address item 1.

**Comment by jaymode** [comment]
Yes upgrading to either 6.2.0 and 6.2.1 does have issues right now.

> Can you please confirm that we cannot build elasticsearch with Java 8 anymore.

Java 9 is a new requirement to build elasticsearch for 6.2+ https://github.com/elastic/elasticsearch/pull/28071.

> Missing CachingRealm

This class will be moved to the same package and artifact as the rest of the classes. This change will come in 6.2.2

**Comment by vshank77** [comment]
Thanks Jay and Jason. 

Java 9 - No worries, I will upgrade and continue to build upon this. 

When is 6.2.2 expected? As I am currently making it work with 6.2.x will make the necessary changes to this REPO and submit a PR.
