### ISSUE TITLE
unknown realm type error

### ISSUE THREAD

**Issue by vinodrodrigo** [elastic/shield-custom-realm-example#5]
I'm having a couple of issues running the custom plugin and would appreciate some help
1. When starting elastic, I get the following error "unknown realm type [custom] set for realm [custom]
2. If I don't include the shield 2.1.1 jar in the plugin folder, I get classdef error for AuthenticationModule. Is this required, or should elastic load the libraries when it loads the shield plugin?

my yml file has the following config

custom1:
  type: custom
  order: 0
  users.vinod.password: hello
  users.vinod.roles: admin

I am using the 2.1.1 custom plugin example
Thanks
Vinod

**Comment by jaymode** [comment]
Hi Vinod, 

We'd be happy to help you out. However, the best place for this discussion would be https://discuss.elastic.co/c/shield and if we find there is a bug/enhancement needed we can open a issue here. I am going to close this issue for now, if you can open the issue on discuss and add the following information:

1. how did you build the plugin?
2. how did you install the plugin?
3. what other plugins do you have installed?
